Repository project-oak/silveroak, pull requests merged in 2021-03, with the labels that each got.

#605 Infrastructure for building Alectryon webpages
  Makefile
  demos/Makefile
  demos/tutorial.v
  doc/demo/alectryon.css
  doc/demo/alectryon.js
  doc/demo/docutils_basic.css
  doc/demo/tango_subtle.css
  doc/demo/tango_subtle.min.css
  doc/demo/tutorial.html
Labels: documentation

#614 Rename the doc directory to docs for GitHub pages
  docs/CoqStyleGuide.md
  docs/arrows.md
  docs/demo/alectryon.css
  docs/demo/alectryon.js
  docs/demo/docutils_basic.css
  docs/demo/tango_subtle.css
  docs/demo/tango_subtle.min.css
  docs/demo/tutorial.html
Labels: documentation

#616 Add _config.yml for GitHub site
  docs/_config.yml
Labels: documentation

#617 Simplify layout for wider text
  docs/_layouts/default.html
Labels: documentation

#619 Add Gemfiles and change font
  docs/Gemfile
  docs/Gemfile.lock
  docs/_layouts/default.html
Labels: documentation

#620 Link to interactive demo from root page
  docs/index.md
Labels: documentation

#621 Change to Roboto font
  docs/_layouts/default.html
Labels: documentation

#612 Rename peel/unpeel to packv and unpackv
  acorn-examples/AdderTree.v
  acorn-examples/IncrDecr.v
  acorn-examples/Sorter.v
  acorn-examples/xilinx/XilinxAdderTree.v
  cava/Cava/Acorn/CavaClass.v
  cava/Cava/Acorn/Combinational.v
  cava/Cava/Acorn/Combinators.v
  cava/Cava/Acorn/Identity.v
  cava/Cava/Acorn/NetlistGeneration.v
  cava/Cava/Acorn/XilinxAdder.v
  cava/Cava/Lib/Multiplexers.v
  cava/Cava/Lib/UnsignedAdders.v
  cava/Cava/Lib/Vec.v
  silveroak-opentitan/aes/Acorn/CipherCircuit.v
  silveroak-opentitan/aes/Acorn/CipherControlCircuit.v
  silveroak-opentitan/aes/Acorn/MixColumnsCircuit.v
  silveroak-opentitan/aes/Acorn/Pkg.v
  silveroak-opentitan/aes/Acorn/ShiftRowsCircuit.v
  silveroak-opentitan/pinmux/Pinmux.v
  tests/Array.v
  tests/DoubleCountBy/ListProofs.v
Labels: cleanup

#626 Rename multistep to simulate
  acorn-examples/AdderTree.v
  acorn-examples/FullAdderExample.v
  acorn-examples/NandGate.v
  acorn-examples/Sorter.v
  acorn-examples/UnsignedAdderExamples.v
  acorn-examples/xilinx/NandLUT.v
  acorn-examples/xilinx/XilinxAdderExamples.v
  acorn-examples/xilinx/XilinxAdderTree.v
  cava/Cava/Acorn/Acorn.v
  cava/Cava/Acorn/Simulation.v
  cava/Cava/Extraction.v
  cava/Cava2HDL.cabal
  silveroak-opentitan/aes/Acorn/AES256Equivalence.v
  silveroak-opentitan/aes/Acorn/AddRoundKeyNetlist.v
  silveroak-opentitan/aes/Acorn/CipherEquivalence.v
  silveroak-opentitan/aes/Acorn/MixColumnsNetlist.v
  silveroak-opentitan/aes/Acorn/ShiftRowsNetlist.v
  silveroak-opentitan/aes/Acorn/SubBytesNetlist.v
  tests/AccumulatingAdderEnable/AccumulatingAdderEnable.v
  tests/AccumulatingAdderEnable/ListProofs.v
  tests/AddWithDelay/AddWithDelay.v
  tests/AddWithDelay/ListProofs.v
  tests/Array.v
  tests/CountBy/CountBy.v
  tests/CountBy/ListProofs.v
  tests/Delay.v
  tests/DoubleCountBy/DoubleCountBy.v
  tests/DoubleCountBy/ListProofs.v
  tests/Instantiate.v
  tests/MuxTests.v
  tests/TestMultiply.v
  tests/xilinx/LUTTests.v
Labels: cleanup

#627 Remove unIdent
  acorn-examples/AdderTree.v
  acorn-examples/Examples.v
  acorn-examples/FullAdderExample.v
  acorn-examples/IncrDecr.v
  acorn-examples/NandGate.v
  acorn-examples/Sorter.v
  acorn-examples/UnsignedAdderExamples.v
  acorn-examples/xilinx/XilinxAdderExamples.v
  acorn-examples/xilinx/XilinxAdderTree.v
  cava/Cava/Acorn/Combinational.v
  cava/Cava/Acorn/CombinationalProperties.v
  cava/Cava/Acorn/Combinators.v
  cava/Cava/Acorn/Identity.v
  cava/Cava/Acorn/Simulation.v
  cava/Cava/Acorn/XilinxAdder.v
  cava/Cava/Lib/FullAdder.v
  cava/Cava/Lib/MultiplexersProperties.v
  cava/Cava/Lib/UnsignedAdderProofs.v
  cava/Cava/Lib/UnsignedAdders.v
  cava/Cava/Lib/VecProperties.v
  cava/Cava/VectorUtils.v
  cava/Cava2HDL.cabal
  silveroak-opentitan/aes/Acorn/AES256Equivalence.v
  silveroak-opentitan/aes/Acorn/AddRoundKeyEquivalence.v
  silveroak-opentitan/aes/Acorn/AddRoundKeyTests.v
  silveroak-opentitan/aes/Acorn/CipherControlCircuit.v
  silveroak-opentitan/aes/Acorn/CipherEquivalence.v
  silveroak-opentitan/aes/Acorn/MixColumnsEquivalence.v
  silveroak-opentitan/aes/Acorn/MixColumnsTests.v
  silveroak-opentitan/aes/Acorn/ShiftRowsEquivalence.v
  silveroak-opentitan/aes/Acorn/ShiftRowsTests.v
  silveroak-opentitan/aes/Acorn/SubBytesEquivalence.v
  silveroak-opentitan/aes/Acorn/SubBytesTests.v
  tests/AccumulatingAdderEnable/ListProofs.v
  tests/AddWithDelay/ListProofs.v
  tests/CountBy/ListProofs.v
  tests/DoubleCountBy/ListProofs.v
  tests/MuxTests.v
  tests/TestMultiply.v
Labels: cleanup

#625 Inverter tutorial
  demos/Makefile
  demos/tutorial.v
  docs/demo/tutorial.html
Labels: documentation

#628 Renaming and tweaks to trees
  acorn-examples/AdderTree.v
  acorn-examples/xilinx/XilinxAdderTree.v
  cava/Cava/Acorn/CombinationalProperties.v
  cava/Cava/Acorn/Combinators.v
  cava/Cava/Extraction.v
  cava/Cava2HDL.cabal
Labels: cleanup

#641 Cleanup of Combinators.v and Adders.v
  cava/Cava/Lib/Adders.v
  cava/Cava/Lib/AddersProperties.v
  cava/Cava/Lib/BitVectorOps.v
  cava/Cava/Lib/CavaPrelude.v
  cava/Cava/Lib/CavaPreludeProperties.v
  cava/Cava/Lib/Combinators.v
  cava/Cava/Lib/CombinatorsProperties.v
  cava/Cava/Lib/LibProperties.v
  cava/Cava/Semantics/Combinational.v
  cava/Cava2HDL.cabal
  examples/UnsignedAdderExamples.v
  examples/xilinx/XilinxAdderExamples.v
  silveroak-opentitan/aes/Impl/AddRoundKeyCircuit.v
  silveroak-opentitan/aes/Impl/AddRoundKeyEquivalence.v
Labels: cleanup

#649 Update docs
  demos/Makefile
  demos/tutorial.v
  docs/_layouts/default.html
  docs/demo/tutorial.html
  docs/index.md
Labels: documentation

#652 Add targets to third_party .PHONY
  third_party/Makefile
Labels: friction

#651 Tutorial: three xor-based examples
  demos/tutorial.v
  docs/demo/tutorial.html
Labels: documentation

#653 Make tutorial support Mac
  docs/demo/alectryon.css
  docs/demo/alectryon.js
  docs/demo/docutils_basic.css
  docs/demo/tutorial.html
Labels: documentation

#659 Make bedrock2 target depend on coqutil
  third_party/Makefile
Labels: friction

#656 Remove options argument from common case netlist generation
  cava/Cava/Core/Netlist.v
  demos/tutorial.v
  examples/AdderTree.v
  examples/FullAdderExample.v
  examples/NandGate.v
  examples/Sorter.v
  examples/UnsignedAdderExamples.v
  examples/xilinx/NandLUT.v
  examples/xilinx/XilinxAdderExamples.v
  examples/xilinx/XilinxAdderTree.v
  silveroak-opentitan/aes/Impl/AddRoundKeyNetlist.v
  silveroak-opentitan/aes/Impl/CipherControlNetlist.v
  silveroak-opentitan/aes/Impl/MixColumnsNetlist.v
  silveroak-opentitan/aes/Impl/ShiftRowsNetlist.v
  silveroak-opentitan/aes/Impl/SubBytesNetlist.v
  silveroak-opentitan/pinmux/Pinmux.v
  tests/AccumulatingAdderEnable/AccumulatingAdderEnable.v
  tests/Array.v
  tests/CountBy/CountBy.v
  tests/Delay.v
  tests/DoubleCountBy/DoubleCountBy.v
  tests/Instantiate.v
  tests/MuxTests.v
  tests/TestMultiply.v
  tests/xilinx/LUTTests.v
Labels: cleanup

#662 Add Cava.Lib.VecConstEq
  cava/Cava/Lib/VecConstEq.v
Labels: good first issue

#665 Add extra information on imports + vectors to the tutorial
  demos/tutorial.v
  docs/demo/tutorial.html
Labels: documentation

#674 Reference
  cava/Cava/Core/CavaClass.v
  cava/Cava/Lib/Adders.v
  cava/Cava/Lib/CavaPrelude.v
  cava/Cava/Lib/Combinators.v
  cava/Cava/Lib/Multiplexers.v
  cava/Cava/Lib/Vec.v
  docs/below_and_col.svg
  docs/loop.svg
  docs/reference.md
Labels: documentation

#677 Remove vector slice from Cava class
  cava/Cava/Core/CavaClass.v
  cava/Cava/NetlistGeneration/NetlistGeneration.v
  cava/Cava/Semantics/Combinational.v
Labels: cleanup

#681 Add constantV to CavaClass
  cava/Cava/Core/CavaClass.v
  cava/Cava/Lib/Vec.v
  cava/Cava/NetlistGeneration/NetlistGeneration.v
  cava/Cava/Semantics/Combinational.v
  docs/reference.md
  silveroak-opentitan/aes/Impl/CipherControlCircuit.v
  silveroak-opentitan/aes/Impl/Pkg.v
  tests/Array.v
Labels: cleanup

#693 Add the first two sequential examples to the tutorial
  cava/Cava/Lib/AddersProperties.v
  demos/Makefile
  demos/tutorial.v
  docs/demo/loop.png
  docs/demo/tutorial.html
Labels: documentation

#695 Add tutorial stylesheet
  demos/tutorial.v
  docs/demo/tutorial.css
  docs/demo/tutorial.html
Labels: documentation

#701 SystemVerilog test for bsort
  cava/Cava2SystemVerilog.hs
  examples/BitonicSorter.v
  examples/ExamplesSV.hs
  examples/MonadExtraction.v
Labels: P2

#705 Remove unused files
  silveroak-opentitan/aes/Spec/InterleavedCipher.v
  silveroak-opentitan/aes/Spec/InterleavedInverseCipher.v
Labels: cleanup

#709 Fix kramdown security vunrelability
  docs/Gemfile.lock
Labels: P0

#702 Add fibonacci example to tutorial
  cava/Cava/Util/BitArithmeticProperties.v
  cava/Cava/Util/List.v
  demos/Makefile
  demos/tutorial.v
  docs/demo/fibonacci.png
  docs/demo/tutorial.html
Labels: documentation
