Repository project-oak/silveroak, pull requests merged in 2021-02, with the labels that each got.

#503 Generate SystemVerilog interfaces with only packed arrays
  cava/.gitignore
  cava/Cava/Netlist.v
  cava/Cava2HDL.cabal
  cava/Cava2SystemVerilog.hs
  cava/SystemVerilogUtils.hs
  cava/TestBench.hs
  investigations/sv-experiments/indexing.sv
  silveroak-opentitan/aes/Acorn/verilator.vlt
  tests/MuxTests.v
Labels: P1

#506 Generate hex literals
  cava/Cava/Acorn/NetlistGeneration.v
  cava/Cava/Signal.v
  cava/Cava2SystemVerilog.hs
Labels: P1

#509 Implement pair selection in terms of array indexing
  cava/Cava2SystemVerilog.hs
  cava/SystemVerilogUtils.hs
Labels: P1

#510 FPGA implementation of Silver Oak aes_sub_bytes
  silveroak-opentitan/aes/Acorn/.gitignore
  silveroak-opentitan/aes/Acorn/Makefile
  silveroak-opentitan/aes/Acorn/README.md
  silveroak-opentitan/aes/Acorn/aes_sub_bytes.tcl
Labels: P1

#515 [aes_mix_columns] Updated FPGA implementation report
  silveroak-opentitan/aes/Acorn/.gitignore
  silveroak-opentitan/aes/Acorn/Makefile
  silveroak-opentitan/aes/Acorn/README.md
  silveroak-opentitan/aes/Acorn/aes_util.tcl
Labels: P1

#518 Pack monad instance into CavaClass
  acorn-examples/AdderTree.v
  acorn-examples/FullAdderExample.v
  acorn-examples/IncrDecr.v
  acorn-examples/NandGate.v
  acorn-examples/Sorter.v
  acorn-examples/UnsignedAdderExamples.v
  acorn-examples/xilinx/NandLUT.v
  acorn-examples/xilinx/XilinxAdderExamples.v
  acorn-examples/xilinx/XilinxAdderTree.v
  cava/Cava/Acorn/CavaClass.v
  cava/Cava/Acorn/CavaPrelude.v
  cava/Cava/Acorn/CombinationalMonad.v
  cava/Cava/Acorn/Combinators.v
  cava/Cava/Acorn/Identity.v
  cava/Cava/Acorn/NetlistGeneration.v
  cava/Cava/Acorn/XilinxAdder.v
  cava/Cava/Lib/BitVectorOps.v
  cava/Cava/Lib/FullAdder.v
  cava/Cava/Lib/UnsignedAdderProofs.v
  cava/Cava/Lib/UnsignedAdders.v
  silveroak-opentitan/aes/Acorn/AES256Equivalence.v
  silveroak-opentitan/aes/Acorn/AddRoundKey.v
  silveroak-opentitan/aes/Acorn/CipherRound.v
  silveroak-opentitan/aes/Acorn/FullCipherEquiv_Assumptions.out
  silveroak-opentitan/aes/Acorn/FullCipherInverse_Assumptions.out
  silveroak-opentitan/aes/Acorn/MixColumnsCircuit.v
  silveroak-opentitan/aes/Acorn/Pkg.v
  silveroak-opentitan/aes/Acorn/ShiftRows.v
  silveroak-opentitan/aes/Acorn/SubBytes.v
  tests/AccumulatingAdderEnable/AccumulatingAdderEnable.v
  tests/AddWithDelay/AddWithDelay.v
  tests/Array.v
  tests/CountBy/CountBy.v
  tests/CountBy/ListProofs.v
  tests/CountBy/TimedProofs.v
  tests/CountBy/VectorProofs.v
  tests/Delay.v
  tests/Instantiate.v
  tests/MuxTests.v
  tests/TestMultiply.v
  tests/xilinx/LUTTests.v
Labels: friction

#519 Remove pairSel from CavaClass
  cava/Cava/Acorn/CavaClass.v
  cava/Cava/Acorn/CavaPrelude.v
  cava/Cava/Acorn/CombinationalMonad.v
  cava/Cava/Acorn/CombinationalProperties.v
  cava/Cava/Acorn/NetlistGeneration.v
  cava/Cava/Acorn/SequentialTimed.v
  cava/Cava/Acorn/SequentialV.v
  cava/Cava/ListUtils.v
  cava/Cava/VectorUtils.v
  silveroak-opentitan/aes/Acorn/CipherEquivalence.v
  tests/AccumulatingAdderEnable/ListProofs.v
Labels: P2

#524 Faster simpl_ident
  cava/Cava/Acorn/Identity.v
Labels: friction

#528 Add instructions executing aes_test.c on FPGA board
  silveroak-opentitan/aes/RunningInOpenTitan.md
Labels: P1, documentation

#537 Document aes_add_round_key correspondance
  silveroak-opentitan/aes/Acorn/README.md
Labels: P1

#538 Performance comparison of OT top-level block vs. Silver Oak
  silveroak-opentitan/aes/Acorn/README.md
Labels: P1

#540 Add `aes_cipher_core` without additional status signals
  silveroak-opentitan/aes/Acorn/Cipher.v
Labels: P1

#551 Compile time evaluation for fst and snd
  cava/Cava2SystemVerilog.hs
Labels: P0

#558 Add local signal declaration for sharing
  cava/Cava/Acorn/CavaClass.v
  cava/Cava/Acorn/CombinationalMonad.v
  cava/Cava/Acorn/NetlistGeneration.v
Labels: P1

#563 Change muxPair to assign result to local signal
  cava/Cava/Acorn/CavaPrelude.v
Labels: P1

#578 Reduce size of aes_mix_columns.sv from 25307 to 9939 lines
  silveroak-opentitan/aes/Acorn/MixColumnsCircuit.v
Labels: P1
